AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
Layout/IndentHeredoc:
  EnforcedStyle: squiggly
Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - 'bin/**/*'
