version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/containers/postgres/Dockerfile
    volumes:
      - ./:/home/root/project
    env_file: .env

  web:
    build:
      context: .
      dockerfile: ./docker/containers/web/Dockerfile
    volumes:
      - ./:/home/dockeruser/project
      - greensteps_gems:/usr/local/bundle
    links:
      - postgres
    env_file: .env

volumes:
  greensteps_gems:
    external:
      name: greensteps_gems
